/* ============================================================
   Interview-Volltexte — Revelations-Gespräche
   ------------------------------------------------------------
   Die Originaltexte (© Phil & Sarah Stokes, clivebarker.info)
   liegen nicht im Repository, sondern werden hier manuell
   eingepflegt (Freigabe der Rechteinhaber vorausgesetzt).

   Zum Befüllen:
   1. Text der Archivseite kopieren (z. B. von
      https://www.clivebarker.info/intsrevel37.html).
   2. Unten zwischen die Backticks einfügen — Wort für Wort.

   Format-Regeln (werden von js/interviews.js geparst):
   - Absätze durch Leerzeilen getrennt
   - Sprecher-Präfixe "Revelations:" und "Clive:" wie im Original
   - Absätze ohne Präfix, die mit einem Anführungszeichen beginnen,
     gelten als Fortsetzung von Clives Antwort
   - Absätze ohne Präfix und Anführungszeichen werden als
     erzählende Zwischentexte kursiv gesetzt
   - Markdown-Bilder werden ignoriert, Markdown-Links auf ihren
     Linktext reduziert — die Bilder platziert die Seite selbst
   ============================================================ */

window.INTERVIEW_TEXTS = window.INTERVIEW_TEXTS || {};

/* ------------------------------------------------------------
   Fear, Love, Story... and Time · Frühjahr 2022
   Quelle: https://www.clivebarker.info/intsrevel37.html
   ------------------------------------------------------------ */
window.INTERVIEW_TEXTS["fear-love-story-and-time"] = `
By Phil & Sarah Stokes, 29 and 31 March, 1, 23 and 26 April and 31 May 2022

With more details over on the news page here, we’ve been hard at work on a book, Clive Barker’s Dark Worlds, which is being published by the Cernunnos imprint of Abrams Books this coming October. The book is a rich, visual journey that covers all aspects of Clive’s creative work, along with Clive’s thoughts on each area and critical and cultural analysis. We hope you like it!

Clive has also been working hard and he was keen to talk about an abundance of new stories for television and why the news on Deep Hill, Abarats Four and Five, the Third book of the Art and other projects has been quiet of late. The interview developed over several conversations, with more details on the projects we've covered below - and several others - to follow, just as soon as we're able to share them...

Revelations : "One thing we want to talk a little about today is the new book coming out from Abrams in October – Clive Barker’s Dark Worlds. So, as you know, we were approached by an editor at Abrams back in the summer of 2020 who is a long time admirer of your work and who wanted to explore the idea of a monograph that covered every aspect of your creativity over the last fifty or so years. Eighteen months on and Dark Worlds is almost locked and you’ve seen the whole book now – images and text – laid out together for the first time."

Clive : "You’ve created a mirror for me to look into, and it’s a bit of a mindblower, frankly, in the best possible way, but it’s such a mindblower that there isn’t a scale on which I can think about this that isn’t preposterous."

Revelations : "In writing the book and going through reviews of your work and reaction to it, spread over five decades, it struck us that, as you’ve often found, while some recognise the scale and extent of diversity in your media, a sizeable number of filmgoers don’t know that you write, some readers might not know how extensively you write poetry, and others may not be familiar with your painting and artwork. Then again, others know a vast amount about you and are keen to read new insight into your thoughts and processes in any medium. What do you see when you look across the diversity of work in Dark Worlds?"

Clive : "I don’t see diversity; I see a single mind manifesting its obsessions through a series of media. And I think what’s interesting is that the media, by their very qualities, bring forth certain aspects of my obsessions. Each of the media, it seems to me, has strengths and weaknesses: a novel gives you an interior life of a character, in a way that a movie doesn’t; a poem gives you incredible intimacy at certain times, in a way that even a novel can’t. There’s a sense in which the way that these things come to me, the way that these things appear in my head, are also very different. Poems can appear literally in the time that I say them – admittedly very few poems, but nonetheless I can simply say a poem as though it’s a conversation. You obviously can’t do that with a movie – at one point I think I said that writing a novel is masturbation and a film is an orgy – it’s an off-colour joke but the fact is it’s true!

"It’s not even the same for each novel – for Imajica I said the least I possibly could in advance to my publisher, and for Sacrament I gave a fairly detailed breakdown. For the two years I wrote Imajica I was entirely on my own and I never showed anything to anybody – I don’t think I even told HarperCollins what I was writing. The same with Thief, I didn’t talk to anyone editorially at all. I gave them not an incredibly detailed, but a reasonably detailed breakdown of what I knew about Sacrament, and it turned out to be a débacle, in the sense that they were appalled by what they were given.

"I want to say something new in the introduction to your book, and there’s not a tone that I, as the subject of this book, can apply to it that does not sound either hopelessly self-serving or pathetically humble. Here is this 350-page book which has an incredible sort of barrage of imagery plus extraordinary writing, your best writing, about all the projects, and the tone of the writing is amazing and I kept thinking what am I going to say that isn’t a just a redundance?

"Maybe I should address why am I obsessed with art? Two metaphysical questions: Why do I make art? Why do we make art? And are those the same question?

"I think art is more important than ever. What art does is something that remains a mystery, even though it’s been done now for ten thousand years, looking back to the images painted on cave walls. What art does in speaking both of the external world and the internal world is without precedent in the human experience. The man who drew the hunt on the walls of a French cave was speaking of himself, and of the hunt, yes? He was present in the act of reporting. He was an imperfect journalist – better than that, he was a confessional journalist. He was, in one sense, an anti-journalist because journalists are taught to be impartial.

"Now for me, and here I am approaching seventy, this mystery remains as profound as ever. I have no idea where poems come from. I was writing to someone, talking about my ineptitude with technology, and he started talking about poetry and I said, well, I think poetry is a mechanism, rhymes are mechanisms, meter is a mechanism; it should not be so difficult for me to understand how to turn on my computer, if I can rhyme ‘innocence’ with ‘in a sense’, but it is!

"Which takes me back I suppose to the nuancing of the intellect about system and scheme. The things which give me greatest pleasure as an admirer of other people’s art, and as an admirer of my own art when it’s good, is elegance of scheme: ‘Nothing ever begins…’ ‘…And this story, having no beginning, will have no end.’ Two lines, intimately connected, with seven hundred pages between them.

"I have always felt that the single most obvious metaphor in my work is a door being opened onto a world that you do not know – yes? And that happens over and over – metaphorically or actually on occasion – over and over and over people fall into carpets, people find themselves washed away by seas, both Quiddity and the Sea of Isabella. In the Quiddity mythology we get to the dream world where we see these visions three times in our lives. There is the symbol at the beginning of the Art book which gives you an entire system, in a way, of metaphysics, both upon the vertical axis and the horizontal axis, with a Christ figure in the middle, a crucified figure, if you will – benignly crucified, if that’s possible. I’m telling you things I know you know, but Gutenberg produced a book called the Maelstrom Grimoire in my own mythology, which actually lays out the position of all the doors. Yes, he published the Bible but the really secret thing, the thing that he was really created to print was this grimoire. The incredibly complicated metaphysic around Kissoon and the Los Alamos nuncio mythology, they’re all connected, and they’ve always been connected in my head.

"I know this is going to sound like free-association but it isn’t, in my head, I think we’re talking about the same things – I think we’re always talking about the same things when we are talking: changing genres; changing modes – everything is a part of everything else.

"I think I try, and fail very often, really try to press the body of my vision into a singularity, which it really doesn’t want to be. On the other hand, if you look at a lot of the things I’ve written: sexuality and the ambiguity of sexuality; how male can become female, how female can become male is something which comes up over and over again. It comes up in the poems: ‘Men, be women!’ ‘Men, be your mothers!’ one of the poems opines. It happens in the novels, it obviously happens in The Madonna in which Garvey wakes up to find he’s become a woman. It happened in the plays and it happened most obviously in Imajica. When I think back about Imajica, which is what, thirty years old, I’m surprised they didn’t argue about that one like they did with Sacrament!

"If I had to choose one thing that brings everything together, it would be ‘change’. Whether it would be Frank rising from the floorboards becoming corporeal again, or whether it’s Harvey turning into a vampire, or Lulu into a fish."

Clive broke off to read us a new opening to Deep Hill that he had written overnight – much more to follow on that over time – before we started to talk about his relative silence over the past several months.

Revelations : "What’s fresh and front of mind?"

Clive : "There’s a lot of things that are front of mind right now.

"There are twenty-five stories in front of me right now. I mean, I’m sitting here with every single surface that I have got around me – six surfaces, tables and a huge desk and so on – covered to capacity with either reference books or drafts of a number of projects."

Revelations : "And lots of those have moved on substantially recently and are really well advanced now."

Clive : "Yes, some of them obviously, like Mercy and the Jackal, which is ready for one last pass and then it’s off, or the poetry – same deal, people know about. But there’s a lot of things that I haven’t talked about because I wasn’t sure if they were absolutely set and going to go. And now I know they are set and are going to go so I think it’s time to talk about them and explain to some extent what I’ve been doing with my imagination for the last year or so.

"Let me say something, this will almost be my philosophy of what I’ve been thinking about television. Streaming television is changing the way we look at entertainment, no question, but it’s also, in its own way, changing in its own ambitions.

"So, I was approached by Warner Bros. last year to do a series of stories, some of which would be taken from the Books of Blood, many of which would be originals, each of which would be twenty, twenty-five minute animations. There’s a science fiction series called Love, Death + Robots which I have watched – there are two seasons of it on Netflix – and have enjoyed. I haven’t enjoyed all of them equally in terms of their aesthetics or their stories, but I think when they’re good they’re very, very good."

Revelations : "Yes, we were finding that we were responding really differently to individual episodes, which speaks to the variety of storytelling styles."

Clive : "The idea of adult animation has always been something I’ve found fascinating but I’ve never really seen it being very aesthetic. Adult animation, at least in America, tends to be about saying naughty words, you know, firstly it was Beavis and Butthead I suppose, and then more recently there’s been much more intense things but they tended to be slightly comedic. But I’ve always thought it was a place to put, for instance, In the Hills, The Cities – it’s very hard to imagine how In the Hills, The Cities gets turned into a live action feature film.

"Warner Bros. came to me, actually a man called Jason DeMarco who is head of adult animation at Warner’s, came to me and said, ‘Listen, I love the Books of Blood, the first thing I’d do is In the Hills, The Cities.’ So that’s what’s happening, that’s what we’re doing. He’s tending to take ambitious visual stories like In the Hills, The Cities but, in addition to the five stories from the Books of Blood that he named, he also wanted me to originate another six, which is what I’ve done. I don’t see any reason why I shouldn’t talk about the contents of those but I’d like to leave that to a second conversation, yes?"

Revelations : "Sure – we have lots to get through here!"

Clive : "What I would say is that my ambition for these stories was and is that they be in no way a diminution of the quality that was in the original Books of Blood. These stories, both in terms of their content and, if you like, their style – though obviously they’re not literary, they’re visual – they needed to sit comfortably with the Books of Blood stories. And I actually ended up creating eleven stories which will go into Mr DeMarco’s compendium, making a total of sixteen. He wants to do eleven at present. Their actual length is hard to be sure of but they won’t be less than twenty minutes apiece. This man is marvellous – he knows my stuff inside out and so does the man who brought me in the first place to Warner Bros., a man called Daniel Dominguez with whom I’m working on the project.

"You know, it’s a Books of Blood project so we may end up calling it The Books of Blood but it’s something that has taken an awful lot of time and creative energy because I was trying, I have been trying to create a body of stories that would be as rich and resonant as the stories in the original Books of Blood. I don’t want to feel that just because I’m writing them in words but creating them as scripts for animation that they should be in any way less powerful, less provocative, less intense, less extreme than the original Books of Blood were. I think I can say confidently that I’ve done everything in my power to make sure that’s the case. None of these are stories that I’ve talked to anyone else about, except to Daniel who I shared them with, so they’re not yesterday’s food warmed up, they’re new narratives with new ideas which are disturbing and all the things I hope the original Books of Blood were. Now, that’s one thing that’s been taking...

"Let me back up. Writing stories is a challenge, and writing a lot of stories is a challenge because my head fills with this stuff and there isn’t room for anything else, you know?"

Revelations : "Yes, it’s an important aspect of the diversity we’ve been talking about – and means that whilst people might see progress on one project, that inevitably takes time away from another project in another medium."

Clive : "That’s so right. So that was, I think, eleven stories so far, plus some which I haven’t yet developed properly. At the same time, I went to my friend Mick Garris, who I’ve known thirty-some years, and I said I wanted to do a series of television projects which would be horror stories set entirely in Britain. I wanted to go back to Britain, to the Motherland and honour and celebrate the fact that a great deal of what is absolutely central to the horror tradition originates in Britain. You know, whether it be Stephenson, who was Scottish of course, whether it be Bram Stoker, who was Irish, Mary Shelley who was English. You know we have a lot of rather less celebrated talents but nevertheless great talents like Arthur Machen; there is an incredible density of dark, dark, dark imaginative work which was created in England, Ireland, Scotland and Wales. I’m sure there are learned books that I haven’t read which pull all that together and explain that but, as I say, I haven’t read them and I thought to myself it’s weird that all this – it’s not just that it’s good writing, it’s actually in many cases the root of horror, at least in its literary form and those stories, those iconic narratives and images became the root for all the Universal Pictures narratives in the ‘30s – yes? Within this very small geographical area come an incredible density of horror images – I shouldn’t say just images – stories. These are stories which are known worldwide – there can’t be too many cultures around the world who do not know the image of Dracula, who do not know the image of the Frankenstein monster, that do not know the image of Jekyll and Hyde… it was the French of course who invented the werewolves, so we can’t lay claim to that…

"In the Books of Blood I’d attempted to write stories that were my own subgenre, if you like, you know, six books in which I would write tales in many different tones and with very many different subtexts but that when taken together would be the attempt to, to misquote Woody Allen who said ‘this movie contains everything I know about sex including several that led to my divorce…’, those original six books were all I could think about horror including several things that led to my state of mind. I wanted to come back to that again and do it for television. Why television? Because it gets to a huge audience and because I love England, I love Wales, I love Scotland, I love Ireland, though in different ways, and I thought it would be a wonderful thing to create narratives that were set in the places that I knew. I mean the places that I’ve been to in those various countries.

"So that’s what I did. I produced ten narratives which I then took to Mick and Mick said, ‘Yeah, I’ll join you on this.’ I took them to my agents and my agents sold them to Shudder.

"So it’s a series of British originals, stories of mine which Mick and I will produce – without overall title right now, but all to be set in Britain. Shudder is very, very clear that what they want is whatever you would call the Barker style or the Barker approach.

"As your phone call came through I was doing a last pass on the first of them, I suppose you’d call it the pilot, which is called London Voodoo, which sort of speaks for itself I suppose. So that’s a total of eleven plus ten, twenty-one narratives, plus Mercy and the Jackal, and the Art 3 and Abarat 4 and 5, all in my head… and Deep Hill…

"London Voodoo is done in the sense that I’ve written a thirty page summary and now we will do the teleplay which will be an hour long. The other nine of those ten stories are already summed up so what I’m saying is there’s been a period in the last seven, eight months where all I’ve done is written stories, and one of the odd things, and you know this very well of me because we’ve talked about it, when I write stories, when I start to create in that mode of story generation, a certain, I suppose it’s chemical almost, some process kicks in which makes me do more and more of it. So by the next time we talk I will give you a number but, in addition to the twenty that I’ve been talking about I’ve also generated a bunch of other stories which I didn’t intend to.

"I get into a state of mind where the creation of story becomes the only thing I can do. The only thing I’m obsessed with. I go to bed thinking about story, I can’t stop thinking about it and for the last six months because I’ve been house-ridden, partly because of Covid, partly because of not feeling good, I’ve been here every day, so fourteen hours a day, writing and I don’t know I’m going to guess forty stories – twenty plus another twenty – narratives are now extant and I can’t explain how this works or why this works it’s just that I suppose in a way I’m like a glutton who once he starts feeding can’t stop feeding. I get… everything presents itself as a form of narrative.

"The reason I want to talk about this, if it would be of interest to you and to everybody who’s reading this is because there is something about seeing things in narrative form which is something I was given, born with I suppose, and I think a lot of other people are born with it obviously, just like people are born with another form of storytelling, which is joke telling. You know, there are people I’m sure in your circle whose conversation is basically jokes – it’s another way of summarising experience but with a funny ending. I summarise experience in a different way and in the last, let’s say eight months or whatever, it so happens the world has presented me with almost endless subject matter for dark stories. This has been a very dark time in our planet’s history, and whether we’re talking about Ukraine, whether we’re talking about Putin, whether we’re talking US politics, whether we’re talking about global warming, it’s hard to keep your eyes open and look without feeling anxiety. Now, the way I deal with anxiety is by telling stories. Stories are structures which contain my unease. By putting a pattern onto that unease. Yes? It doesn’t necessarily mean that by stamping a design upon things that I’m fearful of I make the fear go away, it doesn’t work that way, but what it does do is give me the illusion of control."

Revelations : "When you say you think in a narrative form, do you think visually and then you write it down, or do you think in words and set-pieces and rhythm and cadence?"

Clive : "I don’t do either of those things, Phil. I tell in stories in images, stories in words, story is story, story is a process."

Revelations : "So you work it out of your system?"

Clive : "It’s mathematics, Phil, it’s mathematics. It’s a very complex… I used the word ‘design’ before – so maybe it isn’t mathematics; it’s geometry. There’s a theorem of story, if you will. I mean, I’m playing here a little bit but not too much, the point is, I don’t write stories with images in my head – I don’t have images in my head and then write a story about them: the images come because I am writing a story, yeah?"

Revelations : "The creation of story, all of that sounded, I won’t say idyllic, but solo, solitary."

Clive : "It is, totally solitary."

Revelations : "But when we talk about the seven or eight or past twelve months we know that you’ve had anything but a solitary life because there have been so many people wanting to talk to you about television and movie projects that it’s been a much more active and collaborative twelve months than perhaps anything in the last ten years."

Clive : "I have dealt exclusively… nobody else has been in these talks, I mean my agents have been in the ones I have had conversations in, but the deals that I’ve done I’ve done by myself and then given to my agents. The fact is that when I took this stuff back onto my own shoulders as it were, I go to bed at night exhausted as I have not been exhausted for a very long time – not in a bad way, I’ve just got too many things to deal with. I never finish the day’s work, ever. I should have had the five pages I have left to give to Mick two days ago and I was just too tired by the end of the day to do it. I’m not complaining about that at all.

"Mick is an incredibly self-effacing man and a totally delightful man but his career has often been tied in with Stephen King / Stephen Spielberg terms, very successfully. I am not tied in with either of those guys – I’m not tied in with anything but my own imagination – so there’s a difference in our approach to things. I love what Steve’s done on occasion, I certainly love what Spielberg’s done on occasion but I don’t take either of them as a model."

Revelations : "And that goes back many years, you’ve always said that it’s your take that interests you rather than playing in somebody else’s vision?"

Clive : "Completely. I mean I go back to Blake: ‘Make your own laws or be a slave to another man’s.’ You know, and this is just me speaking, I cannot see the point of spending a life, as I have, creating things and creating them in service of another man’s imagination – that just doesn’t make any sense to me. Now you two better than anybody on the planet know the frailties and the virtues of that approach. Right? I’ve succeeded and I’ve failed, I don’t know in what measure one falls beside the other but, given the choice, I’ll always pursue the road not taken. And, even in the sense that the expectations people have of me: ‘Oh, he’ll write novels of horror for the rest of his life,’ I will not exactly consciously but… I’m just not interested in doing something twice. I think that’s what it is.

"I have no desire whatsoever to create a Middle Earth. None. I have a desire to create fifty Middle Earths, and draw the roads between them – and that’s a very different thing. I think that fantastic worlds can be smothering to the creative impulse because, ‘Make you own laws or be a slave to another man’s’ is not about making a single law, it’s about making many laws. And every world I make has its own laws. All I’m saying is humanity’s imagination should be open to visit all of them."

Revelations : "The Abrams book shows, I think, that’s a theme that has followed through your body of work as a whole. It was always the case, back from when the Arts Council wouldn’t -"

Clive : "- wouldn’t fund me, yeah."

Revelations : "So you’ve been doing this forever, it’s not that you fell into something and then decided actually I’ll adopt a new model now that I’m better known, this was just your modus operandi."

Clive : "Yeah, and I think it comes from a bunch of things; it comes from that Blake quote, but it also comes from the fact that I don’t have an education in any of this: I didn’t go to literary school; I wasn’t taught playwriting; I wasn’t taught filmmaking; I wasn’t taught to paint. Now, none of that is to pat myself on the back and say ‘Hey, you did all this without help,’ because I didn’t. I had lots of help. I just wasn’t schooled in it. And, there are advantages and disadvantages to that, I think. The advantages are that you get to do your own thing. The disadvantage is that because you are doing your own thing, and inventing yourself, as it were, people don’t really like that very much because I think by and large people proceed on the basis of the similarity you have as an artist to other artists. And if you don’t have those similarities, if you are (and this is a pretentious word so maybe this isn’t the right one, but) self-invented, there’s a real danger that people won’t get you."

Revelations : "And also that they don’t have a language with which to talk about you."

Clive : "Which is, I think it’s the same thing, with respect Sarah; they’re not going to get me unless they have a language to talk about me. And my concerns are primarily metaphysical: if I had to think of one thing, if I had to think of one subject, it’s walking through a door into another world. And in that world learning that the world as you were brought up to understand it is not the world as it perhaps is. Over and over and over and over in the books and the paintings, the plays and the movies: ‘He stands before an open door,’ yeah?

"When you look at yourself through the lens of art, as opposed to the lens of biography, you realise they’re one and the same – yes? So when I started to read the book, I found myself overwhelmed by it. There are so many things you’ve reminded me of in it – I’ve never had one of these drug experiences but I think one of them gives you a life-summary, doesn’t it? Where you ingest the drug and suddenly everything comes before you in full colour and so on – that’s what it’s like! This incredible abundance, this incredible diversity. The fact that I am a singular mind viewing what seems to be a great plurality of minds is bewildering, actually, in a great way. I didn’t know how to assess what I was looking at, and I still haven’t been able to. Every page is different to the page before it, and the page that follows; every one. And the material itself is always different.

"The last time we spoke, I made an argument that I thought held water but I don’t think it does – I’ve read most of the book again since, actually last night: I said ‘all of it comes from one place, the past, the future, the dreaming moment between are all one country living one immortal day…’ Bollocks! I mean, in the long term, sure, it may be true if you look inside my head to see how it’s working but when you look at the book it doesn’t seem that way! It seems as though a cluster of faintly unstable minds have got together and told each other stories and painted pictures for each other all night! I think that the fact that the stories and images fly violently from one extreme to another – I mean, there a re pages which are all black and white because the artwork was black and white, there are pages which are brilliant colour, there are pages of ourselves as regular human beings, as it were and as spiritual being pictures. I am completely besotted by the book."

Revelations : "There’s a continuum in it, with your vision striving to be shared and to communicate to others."

Clive : "This is a big year, this is my Biblical span: threescore years and ten and all that this year has given me is appetite!

"I would like to be able to have some influence on the world, that’s what artists seek. Some artists, abstract expressionists or whatever have no desire to connect with the issues of their day, of their world. You can’t go to Pollock if Pollock were alive and say, ‘Well, how do you feel about – what’s the political value of this painting?’ There isn’t any. I have never seen my purpose as the dividing off of my art from the moral issues or amoral or immoral issues of the world. So if you go through the Books of Blood stories one by one you’ll find they’re all about something which is not ‘Boo!’ It’s also true of all the novels and I think as the novels get bigger, as you get to Imajica, I would argue I tried to make it about the eternal negated goddess but, in order to do that, in order to celebrate the eternal feminine I wanted to take it to a greater level and to talk about the things that had been suppressed that are attached to that.

"If we were to be living spiritual lives we would have a planet, we would have a future as a species. If we were alive to the fact that all things are holy, then we would not be raping and violating the planet. We would not be overfishing, I’m not even going to go into this because you know it, it’s not just about power, it’s about power at one remove, which is money, profit, which then becomes power, of course. It’s about the fact that the last fifty years have seen – again, the word – unspeakable levels of profiteering by drug companies, by armies, by police forces and so on and so forth almost all of which are male dominated bastions. I get so stirred up.

"Here I am, at the tender age of sixty-nine, wanting to be fearless, as I was as a kid, you know, and as a younger writer, and knowing there are things I want to be fearless about; stories, ideas. I think we just got to what the introduction is: what are the things that are the common drivers in my work? Fear, Love, Story… And now it’s me that needs to go away and think about that..."

Indeed, having thought about it, Clive came back to us a little while later, confessing that, far from having himself all figured out, the opposite is true. He continually re-assesses his work from new vantage points and sent us a note as he newly recognised the importance of Time across his work.

Clive : "Here’s a strange thing I learned yesterday. The failure of the hadron collider to spit out its exquisite invisible truth delayed our getting any closer to a definition of time. But a little while after discovering this — an hour, perhaps –I had an epiphany.

“It’s probably something you’ve known a long time, but it’s all news to me. The Art Trilogy, The Abarat Quintet and The Thief of Always are all stories that concern themselves with the transformation, the re-designing, of Time.

"In Abarat the hours are an archipelago, in The Art the past, the future and the dreaming moment between are one immortal day, in The Thief of Always to live a day in one house is to lose a year in another, and in Chiliad, I sit by a river that flows both to futurity and back towards a brutal ancient world, while dreaming of the dead being born from corruption to travel back to the mystery of the womb."
`;

/* ------------------------------------------------------------
   Deutsche Fassung (vom Auftraggeber geliefert)
   ------------------------------------------------------------ */
window.INTERVIEW_TEXTS["fear-love-story-and-time:de"] = `
Von Phil & Sarah Stokes, 29. und 31. März, 1., 23. und 26. April sowie 31. Mai 2022

Mit weiteren Details drüben auf der News-Seite: Wir haben hart an einem Buch gearbeitet, Clive Barker's Dark Worlds, das im kommenden Oktober beim Cernunnos-Imprint von Abrams Books erscheint. Das Buch ist eine reichhaltige, visuelle Reise, die alle Aspekte von Clives kreativem Schaffen abdeckt, zusammen mit Clives Gedanken zu jedem Bereich sowie kritischen und kulturellen Analysen. Wir hoffen, es gefällt euch!

Auch Clive hat hart gearbeitet, und er wollte unbedingt über eine Fülle neuer Geschichten fürs Fernsehen sprechen – und darüber, warum es in letzter Zeit so still um Deep Hill, Abarat Vier und Fünf, das dritte Buch der Kunst und andere Projekte war. Das Interview entwickelte sich über mehrere Gespräche hinweg; weitere Details zu den hier behandelten Projekten – und einigen anderen – folgen, sobald wir sie teilen dürfen...

Revelations: „Eine Sache, über die wir heute ein wenig sprechen wollen, ist das neue Buch, das im Oktober bei Abrams erscheint – Clive Barker's Dark Worlds. Wie du weißt, kam im Sommer 2020 ein Lektor von Abrams auf uns zu, ein langjähriger Bewunderer deiner Arbeit, der die Idee einer Monografie ausloten wollte, die jeden Aspekt deiner Kreativität der letzten rund fünfzig Jahre abdeckt. Achtzehn Monate später ist Dark Worlds fast fertig, und du hast jetzt das ganze Buch gesehen – Bilder und Text – zum ersten Mal gemeinsam gesetzt."

Clive: „Ihr habt einen Spiegel für mich geschaffen, in den ich hineinschauen kann, und das ist offen gesagt ziemlich umwerfend, im bestmöglichen Sinne – aber es ist so umwerfend, dass es keinen Maßstab gibt, in dem ich darüber nachdenken kann, der nicht absurd wäre."

Revelations: „Beim Schreiben des Buches und beim Durchgehen von Rezensionen deiner Arbeit und der Reaktionen darauf, verteilt über fünf Jahrzehnte, fiel uns auf – wie du es selbst oft erlebt hast –, dass zwar manche das Ausmaß und die Vielfalt deiner Medien erkennen, aber eine beträchtliche Zahl von Kinogängern gar nicht weiß, dass du schreibst; manche Leser wissen vielleicht nicht, wie umfangreich du Gedichte schreibst, und wieder andere kennen deine Malerei und dein bildnerisches Werk nicht. Andererseits wissen manche enorm viel über dich und sind begierig auf neue Einblicke in deine Gedanken und Prozesse in jedem Medium. Was siehst du, wenn du über die Vielfalt der Arbeiten in Dark Worlds blickst?"

Clive: „Ich sehe keine Vielfalt; ich sehe einen einzelnen Geist, der seine Obsessionen durch eine Reihe von Medien manifestiert. Und ich glaube, das Interessante ist, dass die Medien durch ihre jeweiligen Eigenschaften bestimmte Aspekte meiner Obsessionen hervorbringen. Jedes der Medien hat, so scheint mir, Stärken und Schwächen: Ein Roman gibt dir das Innenleben einer Figur auf eine Weise, wie ein Film es nicht kann; ein Gedicht gibt dir in bestimmten Momenten eine unglaubliche Intimität, wie sie selbst ein Roman nicht erreicht. In gewissem Sinne ist auch die Art, wie diese Dinge zu mir kommen, wie sie in meinem Kopf erscheinen, sehr unterschiedlich. Gedichte können buchstäblich in der Zeit entstehen, in der ich sie ausspreche – zugegeben, nur sehr wenige Gedichte, aber dennoch kann ich ein Gedicht einfach sagen, als wäre es ein Gespräch. Mit einem Film geht das natürlich nicht – irgendwann habe ich mal gesagt, einen Roman zu schreiben sei Masturbation und ein Film eine Orgie – ein anzüglicher Witz, aber die Wahrheit ist: Es stimmt!

„Es ist nicht einmal bei jedem Roman gleich – bei Imajica habe ich meinem Verlag vorab so wenig wie irgend möglich gesagt, und bei Sacrament habe ich eine ziemlich detaillierte Übersicht abgegeben. In den zwei Jahren, in denen ich Imajica schrieb, war ich völlig auf mich allein gestellt und habe niemandem je etwas gezeigt – ich glaube, ich habe HarperCollins nicht einmal gesagt, was ich da schrieb. Genauso bei Thief, da habe ich mit niemandem redaktionell gesprochen. Bei Sacrament habe ich ihnen eine nicht unglaublich detaillierte, aber doch einigermaßen detaillierte Übersicht dessen gegeben, was ich wusste, und es endete in einem Debakel – in dem Sinne, dass sie entsetzt waren über das, was sie bekamen.

„Ich möchte in der Einleitung zu eurem Buch etwas Neues sagen, und es gibt keinen Ton, den ich als Gegenstand dieses Buches anschlagen könnte, der nicht entweder hoffnungslos selbstgefällig oder erbärmlich demütig klänge. Hier ist dieses 350-seitige Buch mit einem unglaublichen Trommelfeuer an Bildern plus außergewöhnlichen Texten, euren besten Texten, über all die Projekte, und der Ton der Texte ist großartig, und ich dachte immer wieder: Was soll ich sagen, das nicht bloß eine Redundanz wäre?

„Vielleicht sollte ich der Frage nachgehen: Warum bin ich von Kunst besessen? Zwei metaphysische Fragen: Warum mache ich Kunst? Warum machen wir Kunst? Und sind das dieselben Fragen?

„Ich glaube, Kunst ist wichtiger denn je. Was Kunst tut, bleibt ein Mysterium, obwohl sie nun seit zehntausend Jahren gemacht wird, wenn man auf die Bilder an den Höhlenwänden zurückblickt. Was Kunst leistet, indem sie sowohl von der äußeren als auch von der inneren Welt spricht, ist ohne Beispiel in der menschlichen Erfahrung. Der Mann, der die Jagd an die Wände einer französischen Höhle zeichnete, sprach von sich selbst und von der Jagd, ja? Er war im Akt des Berichtens anwesend. Er war ein unvollkommener Journalist – besser noch: ein bekennender Journalist. Er war in gewissem Sinne ein Anti-Journalist, denn Journalisten werden gelehrt, unparteiisch zu sein.

„Für mich – und ich gehe hier auf die Siebzig zu – bleibt dieses Mysterium so tief wie eh und je. Ich habe keine Ahnung, woher Gedichte kommen. Ich schrieb neulich jemandem und sprach über meine Unbeholfenheit mit Technik, und er fing an, über Poesie zu reden, und ich sagte: Nun, ich glaube, Poesie ist ein Mechanismus, Reime sind Mechanismen, Metrum ist ein Mechanismus; es dürfte für mich eigentlich nicht so schwer sein zu verstehen, wie man einen Computer einschaltet, wenn ich ‚innocence' auf ‚in a sense' reimen kann – aber es ist es!

„Was mich wohl zurückbringt zur Verfeinerung des Intellekts in Sachen System und Schema. Das, was mir als Bewunderer der Kunst anderer – und als Bewunderer meiner eigenen Kunst, wenn sie gut ist – die größte Freude bereitet, ist die Eleganz des Schemas: ‚Nichts beginnt jemals...' ‚...Und diese Geschichte, die keinen Anfang hat, wird kein Ende haben.' Zwei Zeilen, innig miteinander verbunden, mit siebenhundert Seiten dazwischen.

„Ich habe immer empfunden, dass die offensichtlichste Metapher in meinem Werk eine Tür ist, die sich auf eine Welt öffnet, die du nicht kennst – ja? Und das geschieht wieder und wieder – metaphorisch oder gelegentlich tatsächlich – immer und immer wieder fallen Menschen in Teppiche, werden Menschen von Meeren fortgespült, sowohl von Quiddity als auch vom Meer der Isabella. In der Quiddity-Mythologie gelangen wir in die Traumwelt, wo wir diese Visionen dreimal in unserem Leben sehen. Da ist das Symbol am Anfang des Kunst-Buchs, das einem gewissermaßen ein ganzes System der Metaphysik liefert, sowohl auf der vertikalen als auch auf der horizontalen Achse, mit einer Christusfigur in der Mitte, einer gekreuzigten Figur, wenn man so will – gütig gekreuzigt, falls das möglich ist. Ich erzähle euch Dinge, von denen ich weiß, dass ihr sie kennt, aber Gutenberg hat in meiner eigenen Mythologie ein Buch namens Maelstrom Grimoire gedruckt, das tatsächlich die Lage aller Türen verzeichnet. Ja, er hat die Bibel veröffentlicht, aber das wirklich Geheime, das, wofür er wirklich erschaffen wurde, war der Druck dieses Grimoires. Die unglaublich komplizierte Metaphysik um Kissoon und die Nuncio-Mythologie von Los Alamos – das alles hängt zusammen, und es hat in meinem Kopf immer zusammengehangen.

„Ich weiß, das klingt jetzt nach freier Assoziation, aber das ist es nicht – in meinem Kopf sprechen wir über dieselben Dinge. Ich glaube, wir sprechen immer über dieselben Dinge, wenn wir sprechen: Genres wechseln, Modi wechseln – alles ist Teil von allem anderen.

„Ich glaube, ich versuche – und scheitere sehr oft –, ich versuche wirklich, den Korpus meiner Vision in eine Singularität zu pressen, die er eigentlich gar nicht sein will. Andererseits, wenn man sich viele der Dinge ansieht, die ich geschrieben habe: Sexualität und die Ambiguität der Sexualität; wie Männliches weiblich werden kann, wie Weibliches männlich werden kann – das taucht wieder und wieder auf. Es taucht in den Gedichten auf: ‚Männer, seid Frauen!' ‚Männer, seid eure Mütter!', verkündet eines der Gedichte. Es geschieht in den Romanen, es geschieht offensichtlich in The Madonna, worin Garvey aufwacht und feststellt, dass er zur Frau geworden ist. Es geschah in den Theaterstücken, und am offensichtlichsten geschah es in Imajica. Wenn ich an Imajica zurückdenke – das ist jetzt was, dreißig Jahre her? –, wundert es mich, dass sie darüber nicht so gestritten haben wie über Sacrament!

„Wenn ich eine Sache wählen müsste, die alles zusammenführt, dann wäre es ‚Verwandlung'. Ob es Frank ist, der aus den Dielenbrettern aufsteigt und wieder körperlich wird, oder Harvey, der sich in einen Vampir verwandelt, oder Lulu in einen Fisch."

Clive unterbrach das Gespräch, um uns einen neuen Anfang von Deep Hill vorzulesen, den er über Nacht geschrieben hatte – dazu mit der Zeit noch viel mehr –, bevor wir anfingen, über seine relative Stille der vergangenen Monate zu sprechen.

Revelations: „Was ist frisch und ganz vorne in deinem Kopf?"

Clive: „Da sind gerade eine Menge Dinge ganz vorne in meinem Kopf.

„Vor mir liegen in diesem Moment fünfundzwanzig Geschichten. Ich sitze hier, und jede einzelne Fläche um mich herum – sechs Flächen, Tische und ein riesiger Schreibtisch und so weiter – ist bis zum Rand bedeckt, entweder mit Nachschlagewerken oder mit Entwürfen einer Reihe von Projekten."

Revelations: „Und viele davon sind in letzter Zeit substanziell vorangekommen und jetzt wirklich weit fortgeschritten."

Clive: „Ja, manche offensichtlich, wie Mercy and the Jackal, das bereit für einen letzten Durchgang ist und dann rausgeht, oder die Gedichte – dasselbe, davon wissen die Leute. Aber es gibt vieles, worüber ich nicht gesprochen habe, weil ich nicht sicher war, ob es absolut feststeht und wirklich kommt. Und jetzt weiß ich, dass es feststeht und kommen wird, also denke ich, es ist Zeit, darüber zu sprechen und ein Stück weit zu erklären, was ich im letzten Jahr oder so mit meiner Vorstellungskraft angestellt habe.

„Lasst mich etwas sagen, das fast meine Philosophie dessen ist, was ich über Fernsehen gedacht habe. Streaming-Fernsehen verändert die Art, wie wir Unterhaltung betrachten, keine Frage, aber es verändert auf seine Weise auch die eigenen Ambitionen.

„Also, Warner Bros. kam letztes Jahr auf mich zu, um eine Reihe von Geschichten zu machen, von denen einige aus den Books of Blood stammen würden, viele aber Originale wären, jede davon eine zwanzig-, fünfundzwanzigminütige Animation. Es gibt eine Science-Fiction-Serie namens Love, Death + Robots, die ich gesehen habe – es gibt zwei Staffeln davon auf Netflix – und die mir gefallen hat. Nicht alle Folgen haben mir gleichermaßen gefallen, was ihre Ästhetik oder ihre Geschichten angeht, aber ich finde: Wenn sie gut sind, sind sie sehr, sehr gut."

Revelations: „Ja, wir haben festgestellt, dass wir auf einzelne Episoden ganz unterschiedlich reagiert haben, was für die Vielfalt der Erzählstile spricht."

Clive: „Die Idee der Erwachsenen-Animation hat mich immer fasziniert, aber ich habe sie nie wirklich als sehr ästhetisch erlebt. Erwachsenen-Animation, zumindest in Amerika, dreht sich meist darum, unanständige Wörter zu sagen – zuerst war es wohl Beavis and Butthead, und in jüngerer Zeit gab es deutlich intensivere Sachen, aber die waren tendenziell leicht komödiantisch. Ich habe aber immer gedacht, das wäre der richtige Ort für, zum Beispiel, In the Hills, the Cities – es ist sehr schwer vorstellbar, wie In the Hills, the Cities zu einem Realfilm werden könnte.

„Warner Bros. kam auf mich zu – genauer gesagt ein Mann namens Jason DeMarco, der Leiter der Erwachsenen-Animation bei Warner, kam zu mir und sagte: ‚Hör zu, ich liebe die Books of Blood, das Erste, was ich machen würde, wäre In the Hills, the Cities.' Und genau das passiert jetzt, genau das machen wir. Er nimmt sich bevorzugt ambitionierte visuelle Geschichten wie In the Hills, the Cities vor, aber zusätzlich zu den fünf Geschichten aus den Books of Blood, die er genannt hat, wollte er auch, dass ich weitere sechs neu erschaffe – was ich getan habe. Ich sehe keinen Grund, warum ich nicht über deren Inhalt sprechen sollte, aber das würde ich gern für ein zweites Gespräch aufheben, ja?"

Revelations: „Klar – wir haben hier ohnehin viel durchzugehen!"

Clive: „Was ich sagen möchte: Mein Anspruch an diese Geschichten war und ist, dass sie in keiner Weise eine Minderung der Qualität darstellen, die in den ursprünglichen Books of Blood steckte. Diese Geschichten mussten, sowohl inhaltlich als auch, wenn man so will, stilistisch – auch wenn sie natürlich nicht literarisch, sondern visuell sind –, bequem neben den Geschichten der Books of Blood bestehen können. Und tatsächlich habe ich am Ende elf Geschichten erschaffen, die in Mr. DeMarcos Kompendium eingehen werden, insgesamt also sechzehn. Er möchte derzeit elf umsetzen. Ihre tatsächliche Länge lässt sich schwer sicher sagen, aber sie werden nicht kürzer als zwanzig Minuten pro Stück sein. Dieser Mann ist wunderbar – er kennt meine Sachen in- und auswendig, genau wie der Mann, der mich überhaupt erst zu Warner Bros. gebracht hat, ein Mann namens Daniel Dominguez, mit dem ich an dem Projekt arbeite.

„Wisst ihr, es ist ein Books-of-Blood-Projekt, also nennen wir es am Ende vielleicht The Books of Blood, aber es hat furchtbar viel Zeit und kreative Energie gekostet, weil ich versucht habe – und immer noch versuche –, einen Korpus von Geschichten zu erschaffen, der so reich und resonant ist wie die Geschichten der ursprünglichen Books of Blood. Ich will nicht das Gefühl haben, dass sie – nur weil ich sie in Worten schreibe, aber als Drehbücher für Animation anlege – in irgendeiner Weise weniger kraftvoll, weniger provokant, weniger intensiv, weniger extrem sein sollten, als es die ursprünglichen Books of Blood waren. Ich glaube, ich kann mit Zuversicht sagen, dass ich alles in meiner Macht Stehende getan habe, um das sicherzustellen. Keine dieser Geschichten habe ich mit irgendjemandem sonst besprochen, außer mit Daniel, dem ich sie gezeigt habe – es ist also nicht das Essen von gestern, wieder aufgewärmt, es sind neue Erzählungen mit neuen Ideen, die verstörend sind und all das, was die ursprünglichen Books of Blood hoffentlich waren. Nun, das ist eine Sache, die Zeit gekostet hat...

„Lasst mich einen Schritt zurückgehen. Geschichten zu schreiben ist eine Herausforderung, und viele Geschichten zu schreiben ist eine Herausforderung, weil sich mein Kopf mit diesem Stoff füllt und für nichts anderes mehr Platz bleibt, versteht ihr?"

Revelations: „Ja, das ist ein wichtiger Aspekt der Vielfalt, über die wir gesprochen haben – und bedeutet, dass Fortschritt bei einem Projekt zwangsläufig Zeit von einem anderen Projekt in einem anderen Medium abzieht."

Clive: „Ganz genau. Das waren also, glaube ich, bislang elf Geschichten, plus einige, die ich noch nicht richtig entwickelt habe. Zur gleichen Zeit ging ich zu meinem Freund Mick Garris, den ich seit über dreißig Jahren kenne, und sagte, ich wolle eine Reihe von Fernsehprojekten machen, Horrorgeschichten, die vollständig in Großbritannien angesiedelt sind. Ich wollte zurück nach Großbritannien, ins Mutterland, und die Tatsache ehren und feiern, dass ein großer Teil dessen, was absolut zentral für die Horror-Tradition ist, aus Großbritannien stammt. Ob es nun Stephenson ist – der natürlich Schotte war –, ob Bram Stoker, der Ire war, Mary Shelley, die Engländerin war. Wir haben auch eine Menge weniger gefeierter Talente, aber dennoch großer Talente wie Arthur Machen; es gibt eine unglaubliche Dichte dunkler, dunkler, dunkler imaginativer Werke, die in England, Irland, Schottland und Wales entstanden sind. Sicher gibt es gelehrte Bücher, die ich nicht gelesen habe, die das alles zusammenführen und erklären, aber wie gesagt, ich habe sie nicht gelesen, und ich dachte mir: Es ist seltsam, dass all das – es ist ja nicht nur gutes Schreiben, es ist in vielen Fällen tatsächlich die Wurzel des Horrors, zumindest in seiner literarischen Form, und diese Geschichten, diese ikonischen Erzählungen und Bilder wurden zur Wurzel für all die Universal-Pictures-Erzählungen der Dreißigerjahre – ja? Aus diesem sehr kleinen geografischen Raum kommt eine unglaubliche Dichte von Horror-Bildern – ich sollte nicht nur Bilder sagen – Geschichten. Das sind Geschichten, die weltweit bekannt sind – es kann nicht viele Kulturen auf der Welt geben, die das Bild Draculas nicht kennen, die das Bild des Frankenstein-Monsters nicht kennen, die das Bild von Jekyll und Hyde nicht kennen... die Werwölfe haben natürlich die Franzosen erfunden, das können wir also nicht für uns beanspruchen...

„In den Books of Blood hatte ich versucht, Geschichten zu schreiben, die mein eigenes Subgenre waren, wenn man so will – sechs Bücher, in denen ich Erzählungen in vielen verschiedenen Tonlagen und mit sehr vielen verschiedenen Subtexten schreiben würde, die aber, zusammengenommen, der Versuch wären – um Woody Allen falsch zu zitieren, der sagte: ‚Dieser Film enthält alles, was ich über Sex weiß, einschließlich einiger Dinge, die zu meiner Scheidung geführt haben...' –, diese ursprünglichen sechs Bücher waren alles, was ich über Horror denken konnte, einschließlich einiger Dinge, die zu meinem Geisteszustand geführt haben. Ich wollte dahin zurückkehren und es fürs Fernsehen tun. Warum Fernsehen? Weil es ein riesiges Publikum erreicht und weil ich England liebe, ich liebe Wales, ich liebe Schottland, ich liebe Irland, wenn auch auf unterschiedliche Weise, und ich dachte, es wäre etwas Wunderbares, Erzählungen zu schaffen, die an den Orten spielen, die ich kannte. Ich meine die Orte, an denen ich in diesen verschiedenen Ländern gewesen bin.

„Also habe ich genau das getan. Ich habe zehn Erzählungen produziert, die ich dann zu Mick brachte, und Mick sagte: ‚Ja, da bin ich dabei.' Ich brachte sie zu meinen Agenten, und meine Agenten verkauften sie an Shudder.

„Es ist also eine Reihe britischer Originale, Geschichten von mir, die Mick und ich produzieren werden – im Moment ohne Gesamttitel, aber alle in Großbritannien angesiedelt. Shudder ist sehr, sehr klar darin, dass sie genau das wollen, was man den Barker-Stil oder den Barker-Ansatz nennen würde.

„Als euer Anruf durchkam, war ich gerade beim letzten Durchgang der ersten davon – ich nehme an, man würde es den Pilotfilm nennen –, die London Voodoo heißt, was wohl für sich selbst spricht. Das macht also insgesamt elf plus zehn, einundzwanzig Erzählungen, plus Mercy and the Jackal und Art 3 und Abarat 4 und 5, alles in meinem Kopf... und Deep Hill...

„London Voodoo ist fertig in dem Sinne, dass ich eine dreißigseitige Zusammenfassung geschrieben habe, und jetzt machen wir das Teleplay, das eine Stunde lang sein wird. Die anderen neun dieser zehn Geschichten sind bereits zusammengefasst. Was ich also sage: Es gab in den letzten sieben, acht Monaten eine Phase, in der ich nichts anderes getan habe, als Geschichten zu schreiben, und eines der seltsamen Dinge – und ihr kennt das sehr gut von mir, weil wir darüber gesprochen haben: Wenn ich Geschichten schreibe, wenn ich in diesen Modus der Geschichtenerzeugung eintrete, setzt ein bestimmter, ich nehme an fast chemischer, irgendein Prozess ein, der mich dazu bringt, immer mehr davon zu tun. Bis zum nächsten Mal, wenn wir sprechen, nenne ich euch eine Zahl, aber zusätzlich zu den zwanzig, von denen ich gesprochen habe, habe ich noch einen Haufen weiterer Geschichten hervorgebracht, die ich gar nicht beabsichtigt hatte.

„Ich gerate in einen Geisteszustand, in dem das Erschaffen von Geschichten das Einzige wird, was ich tun kann. Das Einzige, wovon ich besessen bin. Ich gehe ins Bett und denke an Geschichten, ich kann nicht aufhören, daran zu denken, und in den letzten sechs Monaten – weil ich ans Haus gefesselt war, teils wegen Covid, teils weil es mir nicht gut ging – war ich jeden Tag hier, also vierzehn Stunden am Tag, schreibend, und ich weiß nicht, ich schätze mal vierzig Geschichten – zwanzig plus weitere zwanzig – Erzählungen existieren jetzt, und ich kann nicht erklären, wie das funktioniert oder warum das funktioniert; ich nehme an, ich bin auf gewisse Weise wie ein Vielfraß, der, wenn er einmal zu essen anfängt, nicht mehr aufhören kann. Ich... alles präsentiert sich mir als eine Form von Erzählung.

„Der Grund, warum ich darüber sprechen will – falls es euch und alle, die das lesen, interessiert –, ist, dass es etwas gibt an diesem Sehen der Dinge in erzählerischer Form, das mir gegeben wurde, mit dem ich wohl geboren wurde, und ich glaube, viele andere Menschen werden offensichtlich auch damit geboren, so wie Menschen mit einer anderen Form des Geschichtenerzählens geboren werden, nämlich dem Witzeerzählen. Es gibt sicher Leute in eurem Umfeld, deren Konversation im Grunde aus Witzen besteht – das ist eine andere Art, Erfahrung zusammenzufassen, nur mit einer Pointe am Ende. Ich fasse Erfahrung auf andere Weise zusammen, und in den letzten, sagen wir, acht Monaten oder so hat mir die Welt zufällig fast endlosen Stoff für dunkle Geschichten geliefert. Dies ist eine sehr dunkle Zeit in der Geschichte unseres Planeten, und ob wir über die Ukraine sprechen, ob wir über Putin sprechen, ob wir über die US-Politik sprechen, ob wir über die Erderwärmung sprechen – es ist schwer, die Augen offen zu halten und hinzusehen, ohne Angst zu empfinden. Nun, die Art, wie ich mit Angst umgehe, ist das Erzählen von Geschichten. Geschichten sind Strukturen, die mein Unbehagen fassen. Indem sie diesem Unbehagen ein Muster aufprägen. Ja? Das heißt nicht unbedingt, dass ich, indem ich den Dingen, die ich fürchte, ein Design aufstemple, die Furcht verschwinden lasse – so funktioniert es nicht –, aber was es tut, ist, mir die Illusion von Kontrolle zu geben."

Revelations: „Wenn du sagst, du denkst in erzählerischer Form – denkst du visuell und schreibst es dann auf, oder denkst du in Worten und Szenen und Rhythmus und Kadenz?"

Clive: „Ich tue keins von beidem, Phil. Ich erzähle in Geschichten in Bildern, Geschichten in Worten – Geschichte ist Geschichte, Geschichte ist ein Prozess."

Revelations: „Du arbeitest es also aus deinem System heraus?"

Clive: „Es ist Mathematik, Phil, es ist Mathematik. Es ist eine sehr komplexe... Ich habe vorhin das Wort ‚Design' benutzt – vielleicht ist es also keine Mathematik; es ist Geometrie. Es gibt ein Theorem der Geschichte, wenn man so will. Ich spiele hier ein bisschen, aber nicht zu sehr; der Punkt ist: Ich schreibe keine Geschichten mit Bildern im Kopf – ich habe nicht Bilder im Kopf und schreibe dann eine Geschichte über sie: Die Bilder kommen, weil ich eine Geschichte schreibe, ja?"

Revelations: „Das Erschaffen von Geschichten, all das klang – ich will nicht sagen idyllisch, aber solo, einsam."

Clive: „Ist es, vollkommen einsam."

Revelations: „Aber wenn wir über die letzten sieben, acht oder zwölf Monate sprechen, wissen wir, dass du alles andere als ein einsames Leben hattest, weil so viele Leute mit dir über Fernseh- und Filmprojekte sprechen wollten, dass es zwölf deutlich aktivere und kollaborativere Monate waren als vielleicht alles in den letzten zehn Jahren."

Clive: „Ich habe ausschließlich selbst verhandelt... niemand sonst war in diesen Gesprächen – ich meine, meine Agenten waren bei denen dabei, in denen ich Gespräche geführt habe, aber die Deals, die ich gemacht habe, habe ich allein gemacht und dann meinen Agenten übergeben. Tatsache ist: Seit ich dieses Zeug sozusagen wieder auf meine eigenen Schultern genommen habe, gehe ich abends erschöpft ins Bett, wie ich seit sehr langer Zeit nicht mehr erschöpft war – nicht auf schlechte Weise, ich habe einfach zu viele Dinge zu erledigen. Ich werde mit dem Tagespensum nie fertig, niemals. Ich hätte die fünf Seiten, die mir noch fehlen, schon vor zwei Tagen an Mick geben sollen, und ich war am Ende des Tages einfach zu müde dafür. Ich beklage mich darüber überhaupt nicht.

„Mick ist ein unglaublich zurückhaltender Mann und ein absolut entzückender Mann, aber seine Karriere war oft an Stephen-King-/Steven-Spielberg-Kategorien gebunden, sehr erfolgreich. Ich bin an keinen dieser beiden gebunden – ich bin an nichts gebunden außer an meine eigene Vorstellungskraft –, also gibt es einen Unterschied in unserer Herangehensweise. Ich liebe, was Steve gelegentlich gemacht hat, ich liebe gewiss, was Spielberg gelegentlich gemacht hat, aber ich nehme keinen von beiden als Vorbild."

Revelations: „Und das reicht viele Jahre zurück – du hast immer gesagt, dass es deine eigene Sichtweise ist, die dich interessiert, statt in der Vision eines anderen zu spielen?"

Clive: „Vollkommen. Ich komme immer wieder auf Blake zurück: ‚Mach deine eigenen Gesetze oder sei der Sklave der Gesetze eines anderen.' Und das bin jetzt nur ich, der spricht: Ich kann keinen Sinn darin sehen, ein Leben damit zu verbringen, wie ich es getan habe, Dinge zu erschaffen – und sie im Dienst der Vorstellungskraft eines anderen Mannes zu erschaffen; das ergibt für mich einfach keinen Sinn. Nun kennt ihr zwei besser als irgendjemand sonst auf diesem Planeten die Schwächen und die Tugenden dieses Ansatzes. Richtig? Ich habe Erfolg gehabt und ich bin gescheitert, ich weiß nicht, in welchem Verhältnis das eine zum anderen steht, aber wenn ich die Wahl habe, werde ich immer den nicht begangenen Weg wählen. Und selbst was die Erwartungen angeht, die die Leute an mich haben: ‚Oh, der wird für den Rest seines Lebens Horrorromane schreiben' – ich werde, nicht unbedingt bewusst, aber... Ich habe einfach kein Interesse daran, etwas zweimal zu tun. Ich glaube, das ist es.

„Ich habe nicht das geringste Verlangen, ein Mittelerde zu erschaffen. Keines. Ich habe das Verlangen, fünfzig Mittelerden zu erschaffen – und die Straßen zwischen ihnen zu zeichnen –, und das ist etwas ganz anderes. Ich glaube, fantastische Welten können den kreativen Impuls ersticken, denn ‚Mach deine eigenen Gesetze oder sei der Sklave der Gesetze eines anderen' bedeutet nicht, ein einziges Gesetz zu machen, sondern viele Gesetze. Und jede Welt, die ich erschaffe, hat ihre eigenen Gesetze. Alles, was ich sage, ist: Die Vorstellungskraft der Menschheit sollte offen dafür sein, sie alle zu besuchen."

Revelations: „Das Abrams-Buch zeigt, denke ich, dass sich dieses Thema durch dein Gesamtwerk zieht. Das war schon immer so, seit damals, als der Arts Council nicht –"

Clive: „– mich nicht fördern wollte, ja."

Revelations: „Du machst das also schon immer so; es ist nicht so, dass du in etwas hineingeraten bist und dann beschlossen hast: Jetzt, wo ich bekannter bin, übernehme ich ein neues Modell. Das war einfach dein Modus Operandi."

Clive: „Ja, und ich glaube, das kommt aus mehreren Dingen; es kommt aus diesem Blake-Zitat, aber es kommt auch daher, dass ich in nichts davon eine Ausbildung habe: Ich war auf keiner Literaturschule; mir wurde nicht das Schreiben von Theaterstücken beigebracht; mir wurde nicht das Filmemachen beigebracht; mir wurde nicht das Malen beigebracht. Nun, nichts davon soll heißen, dass ich mir selbst auf die Schulter klopfe und sage: ‚Hey, du hast das alles ohne Hilfe geschafft' – denn das habe ich nicht. Ich hatte viel Hilfe. Ich wurde nur nicht darin geschult. Und das hat, glaube ich, Vor- und Nachteile. Der Vorteil ist, dass man sein eigenes Ding machen kann. Der Nachteil ist: Weil man sein eigenes Ding macht und sich sozusagen selbst erfindet, mögen die Leute das nicht besonders, denn ich glaube, im Großen und Ganzen orientieren sich die Leute an der Ähnlichkeit, die man als Künstler mit anderen Künstlern hat. Und wenn man diese Ähnlichkeiten nicht hat, wenn man (und das ist ein prätentiöses Wort, also ist es vielleicht nicht das richtige) selbsterfunden ist, besteht die reale Gefahr, dass die Leute einen nicht verstehen."

Revelations: „Und auch, dass sie keine Sprache haben, mit der sie über dich sprechen können."

Clive: „Was, glaube ich, dasselbe ist, bei allem Respekt, Sarah: Sie werden mich nicht verstehen, wenn sie keine Sprache haben, um über mich zu sprechen. Und meine Anliegen sind in erster Linie metaphysisch: Wenn ich an eine einzige Sache denken müsste, an ein einziges Thema, dann ist es das Durchschreiten einer Tür in eine andere Welt. Und in dieser Welt zu lernen, dass die Welt, wie man sie zu verstehen erzogen wurde, nicht die Welt ist, wie sie vielleicht ist. Wieder und wieder und wieder und wieder, in den Büchern und den Gemälden, den Theaterstücken und den Filmen: ‚Er steht vor einer offenen Tür', ja?

„Wenn man sich selbst durch die Linse der Kunst betrachtet statt durch die Linse der Biografie, erkennt man, dass sie ein und dasselbe sind – ja? Als ich also anfing, das Buch zu lesen, war ich davon überwältigt. Es gibt so viele Dinge, an die ihr mich darin erinnert habt – ich habe nie eine dieser Drogenerfahrungen gemacht, aber ich glaube, eine davon beschert einem eine Lebenszusammenfassung, nicht wahr? Wo man die Droge einnimmt und plötzlich alles in voller Farbe vor einem erscheint und so weiter – genau so ist es! Diese unglaubliche Fülle, diese unglaubliche Vielfalt. Die Tatsache, dass ich ein einzelner Geist bin, der auf das blickt, was wie eine große Vielzahl von Geistern erscheint, ist tatsächlich verwirrend, auf großartige Weise. Ich wusste nicht, wie ich einschätzen sollte, was ich da sah, und ich kann es bis heute nicht. Jede Seite ist anders als die Seite davor und die Seite danach; jede einzelne. Und das Material selbst ist immer anders.

„Als wir das letzte Mal sprachen, habe ich ein Argument vorgebracht, von dem ich dachte, es sei stichhaltig, aber das glaube ich nicht mehr – ich habe das meiste des Buches inzwischen noch einmal gelesen, gestern Abend sogar: Ich sagte, ‚alles kommt aus einem Ort, die Vergangenheit, die Zukunft, der träumende Moment dazwischen sind ein Land, das einen unsterblichen Tag lebt...' Quatsch! Ich meine, langfristig mag es stimmen, wenn man in meinen Kopf schaut, um zu sehen, wie er arbeitet, aber wenn man das Buch betrachtet, wirkt es nicht so! Es wirkt, als hätte sich ein Grüppchen leicht labiler Geister zusammengetan und sich die ganze Nacht gegenseitig Geschichten erzählt und Bilder füreinander gemalt! Ich glaube, die Tatsache, dass die Geschichten und Bilder heftig von einem Extrem ins andere springen – ich meine, es gibt Seiten, die ganz schwarzweiß sind, weil das Artwork schwarzweiß war, es gibt Seiten in brillanter Farbe, es gibt Seiten mit uns als gewöhnlichen Menschen, sozusagen, und als Bilder spiritueller Wesen. Ich bin vollkommen vernarrt in das Buch."

Revelations: „Es gibt darin ein Kontinuum: deine Vision, die danach strebt, geteilt zu werden und sich anderen mitzuteilen."

Clive: „Dies ist ein großes Jahr, dies ist meine biblische Lebensspanne: siebzig Jahre – ‚dreimal zwanzig und zehn' – und alles, was mir dieses Jahr gegeben hat, ist Appetit!

„Ich möchte in der Lage sein, einen gewissen Einfluss auf die Welt zu haben – das ist es, was Künstler suchen. Manche Künstler, abstrakte Expressionisten oder wer auch immer, haben kein Verlangen, sich mit den Themen ihrer Zeit, ihrer Welt zu verbinden. Man kann nicht zu Pollock gehen – wenn Pollock noch lebte – und sagen: ‚Nun, wie stehst du zu – was ist der politische Wert dieses Gemäldes?' Es gibt keinen. Ich habe meinen Zweck nie darin gesehen, meine Kunst von den moralischen oder amoralischen oder unmoralischen Fragen der Welt abzutrennen. Wenn man also die Geschichten der Books of Blood eine nach der anderen durchgeht, wird man feststellen, dass sie alle von etwas handeln, das nicht bloß ‚Buh!' ist. Das gilt auch für alle Romane, und ich denke, je größer die Romane werden, wenn man zu Imajica kommt – ich würde behaupten, ich habe versucht, es um die ewige, verleugnete Göttin kreisen zu lassen, aber um das zu tun, um das ewig Weibliche zu feiern, wollte ich es auf eine höhere Ebene heben und über die Dinge sprechen, die unterdrückt worden sind und damit zusammenhängen.

„Wenn wir spirituelle Leben führen würden, hätten wir einen Planeten, hätten wir eine Zukunft als Spezies. Wenn wir uns der Tatsache bewusst wären, dass alle Dinge heilig sind, dann würden wir den Planeten nicht schänden und vergewaltigen. Wir würden nicht überfischen – ich gehe da gar nicht weiter drauf ein, weil ihr das wisst; es geht nicht nur um Macht, es geht um Macht auf Distanz, nämlich Geld, Profit, was dann natürlich wieder zu Macht wird. Es geht darum, dass die letzten fünfzig Jahre – wieder dieses Wort – unsägliche Ausmaße von Profitmacherei gesehen haben, durch Pharmakonzerne, durch Armeen, durch Polizeiapparate und so weiter und so fort, fast alles männerdominierte Bastionen. Ich rege mich da so auf.

„Hier bin ich, im zarten Alter von neunundsechzig, und will furchtlos sein, wie ich es als Kind war, wisst ihr, und als jüngerer Schriftsteller, und ich weiß, es gibt Dinge, bei denen ich furchtlos sein will; Geschichten, Ideen. Ich glaube, wir sind gerade darauf gekommen, was die Einleitung ist: Was sind die gemeinsamen Antriebe in meinem Werk? Furcht, Liebe, Geschichte... Und jetzt bin ich es, der weggehen und darüber nachdenken muss..."

Und tatsächlich: Nachdem er darüber nachgedacht hatte, kam Clive wenig später auf uns zurück und gestand, dass er sich, weit davon entfernt, sich selbst durchschaut zu haben, im Gegenteil ständig neu bewertet. Er betrachtet sein Werk immer wieder von neuen Aussichtspunkten aus und schickte uns eine Notiz, als er gerade neu die Bedeutung der Zeit in seinem Werk erkannt hatte.

Clive: „Hier ist etwas Seltsames, das ich gestern gelernt habe. Das Versagen des Hadronen-Colliders, seine exquisite unsichtbare Wahrheit auszuspucken, hat verzögert, dass wir einer Definition der Zeit näherkommen. Aber eine kleine Weile, nachdem ich das entdeckt hatte – eine Stunde vielleicht –, hatte ich eine Epiphanie.

„Wahrscheinlich ist es etwas, das ihr längst wisst, aber für mich ist es ganz neu. Die Kunst-Trilogie, das Abarat-Quintett und The Thief of Always sind allesamt Geschichten, die sich mit der Verwandlung, der Neugestaltung der Zeit befassen.

„In Abarat sind die Stunden ein Archipel; in der Kunst sind die Vergangenheit, die Zukunft und der träumende Moment dazwischen ein einziger unsterblicher Tag; in The Thief of Always bedeutet ein Tag in dem einen Haus ein verlorenes Jahr in einem anderen; und in Chiliad sitze ich an einem Fluss, der sowohl in die Zukunft fließt als auch zurück in eine brutale alte Welt, während ich davon träume, dass die Toten aus der Verwesung geboren werden, um zurückzureisen zum Mysterium des Mutterleibs."
`;

/* ------------------------------------------------------------
   Talking Of The Painting Of The Abarat · März 2021
   Quelle: https://www.clivebarker.info/intsrevel36.html
   ------------------------------------------------------------ */
window.INTERVIEW_TEXTS["talking-of-the-painting-of-the-abarat"] = `
By Phil & Sarah Stokes, 27 March 2021

As Clive prepared to release a number of works on paper for sale through the Archive, he talked us through each piece and their stories, giving some teaser information on Abarats 4 and 5 and confirming the Theatre Of Blood television project with Mick Garris along the way.

Revelations : "Let's talk through the pieces, starting with The Carrion Bird, shall we?"

Clive : "The first thing I wanted to say is that I think the selection is great because it’s a range of styles, and it’s a range of tones. There's a lot of connective tissue here - it's interesting, these pictures we've picked, because there's so much here of Abarat.

"The Carrion Bird does relate to Abarat but it doesn’t relate to anything that’s happened in Abarat yet, though it will. I know what’s going to happen in Book Five because I’ve drafted Book Four now and so I know what’s going to happen in Book Five.

"There are three matters which are the matters of Abarat: the matter of Love; the matter of War; and the matter of Time, yes? And so what happens in the fifth book is that all three of those things collide and Carrion’s own forces – in terms of the Carrion Birds, after which he’s named – manifest themselves. And this is an image of that."

Clive : "The Day of Colours is also an Abarat picture – because another thing that also happens is that the world of Chickentown gets invaded by the hallucinatory. I can’t say more about that yet but it’s a glorious invasion of colours."

Clive : "The World Walks: I’ve done cities like this before, right? Usually works on paper – convoluted, perhaps even Tuscan towns, or certainly Italian towns, in which you see heaped, as it were, buildings and greenery all together. "And Mater Motley: her war is the second of those three things – the matter of Love, the matter of War, the matter of Time. Mater Motley’s war is not just against Abarat, it’s against everything, and one of the ways that Abarat defends itself is by walking; islands getting up and walking. Hence, The World Walks. "

Clive : "Mater Motley’s Sister – I don’t want to give too much away about this, because it’s spoiling something! But Mater Motley – you know, we know very little about Mater Motley’s background. We know what she did – she set fire to the house and so on, the Midnight Palace, but we don’t really know much about her family, we don’t know much about her love affairs, which are going to be very important in these books, hence the matter of Love – the matter of Love is almost more pertinent to Mater Motley, of all people, than it is to anybody else – and Mater Motley’s sister is a part of that narrative."

Clive : "Killing for the Root is an alchemical image. It belongs with a series of alchemical images I did in black and white for The Illusions Suite. The idea of the picture being cut in half so you have two wounding forces, mutually wounding forces, on the top side. And on the night side of that, something which is either a very early foetal form of a human being or a late foetal form, that is a post-human form, on the lower half."

Clive : "The title on the next picture is Infestation. Infestations – parasitic infestations particularly – are at the very root of things that distress me. And there are billions of that thing, that creature which is painted four, five, six times on that sheet. To give you an example: when we go to Kauai, there are not feral dogs but dogs that have lost their homes and they stay on the beach, they live on the beach, yes? And whenever we would go to Kauai they would find us. And always they are tick-infested, their ears are cities of ticks – hundreds and hundreds and hundreds of them, so we would clean their ears always when we got there and kill the ticks. And I cannot think of a more offensive and disgusting image than that kind of infestation: of things that are very elaborate but are also very numerous.

"So you think of these pale white and blue things, which are probably less than a centimetre in length – I’m talking about the ones in the Infestation painting – less than a centimetre in length, but there are millions of them. And in very extreme cases, in Abarat 4, people become walking infestations of that thing. It’s the worst of bad magic, yes? It’s what Mater Motley does when she’s in a mood!

"Parasitic life is fascinating to me and particularly those particular kinds of parasites (and I’m addressing this in the book) those kind of parasites that eat the interior of their hosts in a certain order, so as to keep the host alive for the longest time. And in a remarkably large number of cases they exit the host – one of two ways – either grossly, because suddenly you have this eruption of larvae, of maggots from a body or else, this happens a lot, they leave the body and leave it intact so the creature then goes on to continue its life – which is rather wonderful in its way! Maggots, too, can be forgiving..."

Clive : "London Ghost – I think that’s sort of explicable – you know I’ve been writing a lot about London because of these stories, and I think you can probably now talk about the fact that I’m doing these Theatre of Blood stories with Mick Garris. This is Clive Barker’s Theatre of Blood. It is ten new, utterly new, stories written in the tradition, if you will, of The Books of Blood, directly in that tradition. In other words, in my head even though we’re changing media I am thinking that these are ten more stories to become the seventh Book of Blood, if you will. And it was Mick’s idea to call it the Theatre of Blood, which I think is perfect.

"Two of them are set in London, and London has always been a city of ghosts and this, I think, is a nineteenth century ghost, judging by his top hat, and that’s all there is to say about him, I think. He doesn’t have a place in the narrative, per se, but he’s there.

"The background is actually ink droplets on water, and then I roughed in the figure itself, let it dry and then overdrew it with oil pastel. I think what’s interesting about London Ghost is how perversely bright the pinks are – they imply that outside that cold (I would suggest that figure is a cold figure), a happiness is going on that he has no access to."

Clive : "This is one of Mater Motley’s fools: 'fools' in the sense that, in Velasquez’s paintings that represent the Spanish kings, the fools in it are very often deformed in some way or another. The famous one, Las Meninas, with all the daughters that’s painted from a point of view with reflections in the mirror and a view into a back room – I think it’s in the Prado? – it’s huge and you can see Velasquez, and they’re all lined up, these little duchesses or princesses, and there are fools there amongst them who are the same size as the children. It’s also very knowing of the children themselves with a very ‘look at me, I’m a princess’ look on their faces, but they also have those formal dresses which make them look like little women, and the girls are probably no more than five, right? And the look on their faces is very, ‘I’m being painted’ you know?

"Unlike this one – you’re very unlikely to be a fool for Mater Motley and have a smile on your face!"

Clive : "This is actually, I have no other title for it than Ghosts in a Fire. It’s actually spirits – again Abarat, and I don’t know if I’ll have this in the book or not – there’s a cloud of black smoke on the left hand side of the painting that refers, I guess, to the fire, but within these uprights of blackened wood there are ghosts..."

Clive : "This is The Good Animal, because another thing that’s going to happen in Abarat is that the look of things is going to be addressed very much more clearly – the things that look monstrous are not always monstrous, yeah? And this is a creature which I suppose if you look at it, with its scorpion tail and its bat-like wings and its certainly bat-like face against the moon, looks like it’s just a monster. But it isn’t, it’s a philosopher."

Clive : "Captain Plain and his ship are at the opening passages of Abarat Four and – how do I explain this without giving too much away – it’s a red ship obviously, so it’s an Abaratian ship and Captain Plain can’t wait for his bride because she’s late and he sails away without her, and that’s part of that narrative."

Clive : "The Sea Comes to Chickentown, which we know the moment of obviously. I wanted to paint something I’d never really tried before, which was to paint a relatively realistic picture of a wave breaking – which is sort of hard to do, I found! And I realised that I couldn’t do my usual thing of painting under-layers – the water had to be transparent, or near-transparent which means I could only get one layer of colour on it – does that make sense?

"So this is a painting made of two colours, blue and white, with just a little bit of green in there as well. There’s only one layer of colour on it as you can see in the physical image – it might be worth taking a closer look at the paper and seeing how little paint there is because this is a piece of pure painting, representational painting. And sometimes less is much, much harder to do than more – and this was a son of a bitch! And I roughed it out first and then I thought I was ready and I wasn’t, and I tried a second time and it came off – I do think you get a sense of that’s a breaking wave."

Clive : "Again, I like the paintings in this selection immensely. I think looking at them like this, you don’t even really notice that they’re works on paper, they could be works on canvas. They’re just nice images, I think, of a very wide variety of things. There’s a little Basquiat in the burned ghosts picture, for instance. The media, just so you know, are all acrylic and water and, on occasion, collage. And then my over-drawing is always oil pastel."

Revelations : "A painting like One of Mater Motley's Fools has many of the same characteristics of one of your canvases though, scratching to reveal under-colours, etc."

Clive : "Yes, I think that’s the most extreme of them, isn’t it, on the other hand a piece like The Day of Colours is very thin – it’s again colour onto water and actually Indian ink in terms of the figure."

Revelations : "And it's a big piece, it's imposing..."

Clive : "Yes, I think it’s important that people know that because when you get a frame around that it’s going to be quite a big piece of work, you’re going to need a big wall for that one!

"On the other hand The World Walks, for instance, which I really do like, is smaller but looks very dense – and the back colour again is very simple, I think there’s yellow, white and blue in there, something like that? And I think there’s only one layer – do you have it in front of you? I think in some places there’s no paint, expanses of white space on it."
`;

/* ------------------------------------------------------------
   Deutsche Fassung (vom Auftraggeber geliefert)
   ------------------------------------------------------------ */
window.INTERVIEW_TEXTS["talking-of-the-painting-of-the-abarat:de"] = `
Von Phil & Sarah Stokes, 27. März 2021

Während Clive eine Reihe von Arbeiten auf Papier für den Verkauf über das Archiv vorbereitete, ging er mit uns jedes einzelne Stück und dessen Geschichte durch, gab dabei einige Teaser-Informationen zu Abarat 4 und 5 und bestätigte nebenbei das Fernsehprojekt Theatre Of Blood mit Mick Garris.

Revelations: „Lass uns die Stücke durchgehen – fangen wir mit The Carrion Bird an, ja?"

Clive: „Das Erste, was ich sagen wollte, ist, dass ich die Auswahl großartig finde, weil sie eine Bandbreite an Stilen und eine Bandbreite an Tönen umfasst. Es gibt hier viel Bindegewebe – es ist interessant, diese Bilder, die wir ausgewählt haben, weil so viel Abarat darin steckt.

„The Carrion Bird bezieht sich durchaus auf Abarat, aber nicht auf etwas, das in Abarat schon geschehen wäre – es wird aber geschehen. Ich weiß, was in Buch Fünf passieren wird, denn ich habe Buch Vier inzwischen im Entwurf fertig, und deshalb weiß ich, was in Buch Fünf passiert.

„Es gibt drei Angelegenheiten, die die Angelegenheiten des Abarat sind: die Sache der Liebe, die Sache des Krieges und die Sache der Zeit, ja? Und was im fünften Buch geschieht, ist, dass alle drei aufeinanderprallen und Carrions eigene Kräfte – in Gestalt der Carrion Birds, der Aasvögel, nach denen er benannt ist – sich manifestieren. Und dies ist ein Bild davon."

Clive: „The Day of Colours ist ebenfalls ein Abarat-Bild – denn eine weitere Sache, die geschieht, ist, dass die Welt von Chickentown vom Halluzinatorischen überfallen wird. Mehr kann ich dazu noch nicht sagen, aber es ist eine glorreiche Invasion der Farben."

Clive: „The World Walks: Ich habe schon früher Städte wie diese gemalt, richtig? Meist Arbeiten auf Papier – verschachtelte, vielleicht sogar toskanische Städte, jedenfalls italienische Städte, in denen man Gebäude und Grün gleichsam aufgetürmt beieinander sieht. Und Mater Motley: Ihr Krieg ist die zweite dieser drei Angelegenheiten – die Sache der Liebe, die Sache des Krieges, die Sache der Zeit. Mater Motleys Krieg richtet sich nicht nur gegen das Abarat, er richtet sich gegen alles, und eine der Arten, wie sich das Abarat verteidigt, ist das Gehen: Inseln, die aufstehen und losgehen. Daher: The World Walks."

Clive: „Mater Motley's Sister – hier will ich nicht zu viel verraten, denn das würde etwas verderben! Aber Mater Motley – wisst ihr, wir wissen sehr wenig über Mater Motleys Hintergrund. Wir wissen, was sie getan hat – sie hat das Haus in Brand gesteckt und so weiter, den Mitternachtspalast –, aber wir wissen nicht wirklich viel über ihre Familie, wir wissen wenig über ihre Liebschaften, die in diesen Büchern sehr wichtig sein werden, daher die Sache der Liebe – die Sache der Liebe betrifft Mater Motley, ausgerechnet sie, fast mehr als irgendjemanden sonst –, und Mater Motleys Schwester ist Teil dieser Erzählung."

Clive: „Killing for the Root ist ein alchemistisches Bild. Es gehört zu einer Serie alchemistischer Bilder, die ich in Schwarzweiß für die Illusions Suite gemacht habe. Die Idee des Bildes ist die Zweiteilung: In der oberen Hälfte zwei verwundende Kräfte, sich gegenseitig verwundende Kräfte. Und auf der Nachtseite davon, in der unteren Hälfte, etwas, das entweder eine sehr frühe fötale Form eines Menschen ist oder eine späte fötale Form – also eine post-menschliche Form."

Clive: „Der Titel des nächsten Bildes ist Infestation. Befall – parasitärer Befall im Besonderen – gehört zur Wurzel der Dinge, die mich verstören. Und es gibt Milliarden von diesem Ding, dieser Kreatur, die vier-, fünf-, sechsmal auf diesem Blatt gemalt ist. Um euch ein Beispiel zu geben: Wenn wir nach Kauai fahren, gibt es dort keine verwilderten Hunde, aber Hunde, die ihr Zuhause verloren haben, und die bleiben am Strand, sie leben am Strand, ja? Und wann immer wir nach Kauai kamen, fanden sie uns. Und immer sind sie von Zecken befallen, ihre Ohren sind Städte aus Zecken – Hunderte und Aberhunderte davon –, also haben wir ihnen, wenn wir ankamen, immer die Ohren gereinigt und die Zecken getötet. Und ich kann mir kein anstößigeres und ekelhafteres Bild vorstellen als diese Art von Befall: Dinge, die sehr ausgeklügelt, aber zugleich sehr zahlreich sind.

„Stellt euch also diese blassen, weiß-blauen Dinger vor, die wahrscheinlich weniger als einen Zentimeter lang sind – ich spreche von denen auf dem Infestation-Gemälde –, weniger als einen Zentimeter lang, aber es gibt Millionen davon. Und in sehr extremen Fällen, in Abarat 4, werden Menschen zu wandelnden Brutstätten dieses Dings. Es ist das Schlimmste an schlechter Magie, ja? Es ist das, was Mater Motley tut, wenn sie schlechte Laune hat!

„Parasitäres Leben fasziniert mich, und besonders jene Arten von Parasiten (und ich behandle das im Buch), die das Innere ihrer Wirte in einer bestimmten Reihenfolge fressen, um den Wirt so lange wie möglich am Leben zu erhalten. Und in bemerkenswert vielen Fällen verlassen sie den Wirt auf eine von zwei Arten – entweder auf abstoßende Weise, weil es plötzlich diesen Ausbruch von Larven, von Maden aus einem Körper gibt, oder aber, und das kommt oft vor, sie verlassen den Körper und lassen ihn intakt zurück, sodass das Geschöpf sein Leben weiterleben kann – was auf seine Weise ziemlich wunderbar ist! Auch Maden können vergeben..."

Clive: „London Ghost – das erklärt sich, denke ich, halbwegs von selbst – ihr wisst, ich habe wegen dieser Geschichten viel über London geschrieben, und ich denke, man kann jetzt wohl darüber sprechen, dass ich diese Theatre-of-Blood-Geschichten mit Mick Garris mache. Es ist Clive Barker's Theatre of Blood. Es sind zehn neue, vollkommen neue Geschichten, geschrieben in der Tradition, wenn man so will, der Books of Blood, unmittelbar in dieser Tradition. Mit anderen Worten: In meinem Kopf – auch wenn wir das Medium wechseln – denke ich mir das als zehn weitere Geschichten, die sozusagen das siebte Book of Blood werden. Und es war Micks Idee, es Theatre of Blood zu nennen, was ich perfekt finde.

„Zwei davon spielen in London, und London war schon immer eine Stadt der Geister, und dies ist, denke ich, ein Geist aus dem neunzehnten Jahrhundert, seinem Zylinder nach zu urteilen, und mehr gibt es über ihn, glaube ich, nicht zu sagen. Er hat keinen Platz in der Erzählung an sich, aber er ist da.

„Der Hintergrund besteht tatsächlich aus Tintentropfen auf Wasser, und dann habe ich die Figur selbst grob angelegt, sie trocknen lassen und anschließend mit Ölpastell überzeichnet. Ich finde, das Interessante an London Ghost ist, wie pervers leuchtend die Rosatöne sind – sie deuten an, dass außerhalb dieser Kälte (ich würde sagen, diese Figur ist eine kalte Figur) ein Glück stattfindet, zu dem er keinen Zugang hat."

Clive: „Dies ist einer von Mater Motleys Narren: ‚Narren' in dem Sinne, wie in Velázquez' Gemälden, die die spanischen Könige darstellen, die Narren darin sehr oft auf die eine oder andere Weise deformiert sind. Das berühmte, Las Meninas, mit all den Töchtern, das aus einem Blickwinkel mit Spiegelungen im Spiegel und einem Blick in einen Hinterraum gemalt ist – ich glaube, es hängt im Prado? –, es ist riesig, und man kann Velázquez sehen, und sie stehen alle aufgereiht, diese kleinen Herzoginnen oder Prinzessinnen, und unter ihnen sind Narren, die dieselbe Größe haben wie die Kinder. Es zeigt auch eine große Bewusstheit der Kinder selbst, mit einem sehr ‚Seht mich an, ich bin eine Prinzessin'-Ausdruck auf ihren Gesichtern, aber sie tragen auch diese förmlichen Kleider, die sie wie kleine Frauen aussehen lassen, und die Mädchen sind wahrscheinlich nicht älter als fünf, richtig? Und der Ausdruck auf ihren Gesichtern ist ganz ‚Ich werde gerade gemalt', versteht ihr?

„Anders als bei diesem hier – als Narr für Mater Motley wird man kaum ein Lächeln im Gesicht tragen!"

Clive: „Für dieses hier habe ich tatsächlich keinen anderen Titel als Ghosts in a Fire. Es sind wirklich Geister – wieder Abarat, und ich weiß nicht, ob es das ins Buch schafft oder nicht –, auf der linken Seite des Gemäldes ist eine schwarze Rauchwolke, die sich, nehme ich an, auf das Feuer bezieht, aber zwischen diesen aufrechten Stämmen aus verkohltem Holz sind Geister..."

Clive: „Dies ist The Good Animal, denn eine weitere Sache, die im Abarat geschehen wird, ist, dass das Aussehen der Dinge sehr viel deutlicher zum Thema wird – die Dinge, die monströs aussehen, sind nicht immer monströs, ja? Und dies ist ein Geschöpf, das, wenn man es betrachtet, mit seinem Skorpionschwanz und seinen fledermausartigen Flügeln und seinem eindeutig fledermausartigen Gesicht vor dem Mond, aussieht, als wäre es einfach ein Monster. Aber das ist es nicht – es ist ein Philosoph."

Clive: „Captain Plain und sein Schiff stehen in den Eröffnungspassagen von Abarat Vier, und – wie erkläre ich das, ohne zu viel zu verraten – es ist offensichtlich ein rotes Schiff, also ein abaratisches Schiff, und Captain Plain kann nicht auf seine Braut warten, weil sie zu spät kommt, und er segelt ohne sie davon, und das ist Teil dieser Erzählung."

Clive: „The Sea Comes to Chickentown – den Moment kennen wir natürlich. Ich wollte etwas malen, das ich vorher nie wirklich versucht hatte: ein relativ realistisches Bild einer brechenden Welle – was ziemlich schwer ist, wie ich feststellen musste! Und mir wurde klar, dass ich nicht wie üblich mit Unterschichten arbeiten konnte – das Wasser musste transparent oder beinahe transparent sein, was bedeutet, dass ich nur eine einzige Farbschicht auftragen konnte – ergibt das Sinn?

„Dies ist also ein Gemälde aus zwei Farben, Blau und Weiß, mit nur einem kleinen bisschen Grün darin. Es liegt nur eine Farbschicht darauf, wie man am physischen Bild sehen kann – es lohnt sich vielleicht, das Papier genauer anzusehen und zu erkennen, wie wenig Farbe darauf ist, denn dies ist ein Stück reiner Malerei, gegenständlicher Malerei. Und manchmal ist weniger sehr viel schwerer zu machen als mehr – und dieses Ding war ein Biest! Ich habe es erst grob skizziert und dachte dann, ich sei bereit, und war es nicht, und beim zweiten Versuch hat es geklappt – ich finde schon, dass man den Eindruck einer brechenden Welle bekommt."

Clive: „Noch einmal: Ich mag die Gemälde in dieser Auswahl ungemein. Wenn man sie so betrachtet, fällt einem, glaube ich, gar nicht wirklich auf, dass es Arbeiten auf Papier sind – es könnten Arbeiten auf Leinwand sein. Es sind einfach schöne Bilder, finde ich, von einer sehr großen Bandbreite an Dingen. Im Bild mit den verbrannten Geistern steckt zum Beispiel ein wenig Basquiat. Die Medien sind, nur damit ihr es wisst, durchweg Acryl und Wasser und gelegentlich Collage. Und meine Überzeichnung ist immer Ölpastell."

Revelations: „Ein Gemälde wie One of Mater Motley's Fools hat allerdings viele Merkmale einer deiner Leinwände – das Kratzen, um darunterliegende Farben freizulegen und so weiter."

Clive: „Ja, ich glaube, das ist das extremste von ihnen, nicht wahr? Andererseits ist ein Stück wie The Day of Colours sehr dünn – wieder Farbe auf Wasser, und bei der Figur tatsächlich Tusche."

Revelations: „Und es ist ein großes Stück, es ist imposant..."

Clive: „Ja, ich finde es wichtig, dass die Leute das wissen, denn wenn man da einen Rahmen drumherum hat, wird das ein ziemlich großes Werk – dafür braucht man eine große Wand!

„Andererseits ist zum Beispiel The World Walks, das ich wirklich sehr mag, kleiner, wirkt aber sehr dicht – und die Hintergrundfarbe ist wieder sehr einfach, ich glaube, da sind Gelb, Weiß und Blau drin, so etwas in der Art? Und ich glaube, es ist nur eine Schicht – habt ihr es vor euch? Ich glaube, an manchen Stellen ist gar keine Farbe, weiße Flächen darauf."
`;
